/**
 * ArchSummaryModal — Feature 5: One-Click Architecture Summary
 *
 * Generates a Markdown-style overview of the workspace from the live graph data.
 * Shows: node counts per type, edge counts per type, hottest files, coupling
 * warnings, and primary entry points.  Includes a "Copy as Markdown" button.
 */

import { useMemo, useState } from 'react'
import { X, Copy, Check, FileText } from 'lucide-react'
import { useAppStore } from '../store/app.store'
import { useGraphStore } from '../store/graph.store'
import { computeBlastRadius, heatToCss } from '../universe/utils/graph-algorithms'

export function ArchSummaryModal() {
    const summaryOpen  = useAppStore(s => s.summaryOpen)
    const setSummaryOpen = useAppStore(s => s.setSummaryOpen)
    const activeWorkspace = useAppStore(s => s.activeWorkspace)
    const nodeHeatmap  = useAppStore(s => s.nodeHeatmap)

    const { nodes, edges } = useGraphStore()

    const [copied, setCopied] = useState(false)

    const summary = useMemo(() => {
        if (!nodes.length) return null

        // Count nodes by type
        const byType: Record<string, number> = {}
        for (const n of nodes) byType[n.type] = (byType[n.type] ?? 0) + 1

        // Count edges by type
        const edgesByType: Record<string, number> = {}
        for (const e of edges) edgesByType[e.type] = (edgesByType[e.type] ?? 0) + 1

        // Hottest nodes (from heatmap)
        const hotNodes = Object.entries(nodeHeatmap)
            .sort(([, a], [, b]) => b - a)
            .slice(0, 5)
            .map(([nodeId, heat]) => {
                const node = nodes.find(n => n.id === nodeId)
                return node ? { name: node.name, type: node.type, heat } : null
            })
            .filter(Boolean) as { name: string; type: string; heat: number }[]

        // Coupling: find nodes with highest blast radius
        const couplingWarnings: { name: string; type: string; radius: number }[] = []
        for (const n of nodes) {
            const rm = computeBlastRadius(n.id, edges, 3)
            if (rm.size >= 6) {
                couplingWarnings.push({ name: n.name, type: n.type, radius: rm.size })
            }
        }
        couplingWarnings.sort((a, b) => b.radius - a.radius)

        // Entry points — agents + modules with no incoming edges
        const hasIncoming = new Set(edges.map(e => e.toId))
        const entryPoints = nodes.filter(n =>
            (n.type === 'agent' || n.type === 'module') && !hasIncoming.has(n.id)
        ).slice(0, 5)

        return { byType, edgesByType, hotNodes, couplingWarnings: couplingWarnings.slice(0, 5), entryPoints }
    }, [nodes, edges, nodeHeatmap])

    const markdownText = useMemo(() => {
        if (!summary) return ''
        const lines: string[] = [
            `# ${activeWorkspace?.name ?? 'Workspace'} — Architecture Summary`,
            ``,
            `> Generated by Kosmos on ${new Date().toLocaleDateString()}`,
            ``,
            `## Overview`,
            `**${nodes.length} nodes** · **${edges.length} edges**`,
            ``,
            `### Node Types`,
            ...Object.entries(summary.byType)
                .sort(([,a],[,b]) => b - a)
                .map(([type, count]) => `- **${count}** ${type.replace('_', ' ')}`),
            ``,
            `### Edge Types`,
            ...Object.entries(summary.edgesByType)
                .sort(([,a],[,b]) => b - a)
                .map(([type, count]) => `- **${count}** ${type}`),
        ]

        if (summary.entryPoints.length > 0) {
            lines.push(``, `## Entry Points`, ...summary.entryPoints.map(n => `- \`${n.name}\` _(${n.type})_`))
        }

        if (summary.hotNodes.length > 0) {
            lines.push(``, `## Hottest Files (by session frequency)`,
                ...summary.hotNodes.map(n => `- \`${n.name}\` — ${Math.round(n.heat * 100)}% frequency`)
            )
        }

        if (summary.couplingWarnings.length > 0) {
            lines.push(``, `## ⚠️ High-Coupling Nodes`,
                ...summary.couplingWarnings.map(w =>
                    `- \`${w.name}\` (${w.type}) — **${w.radius} nodes** in blast radius`
                )
            )
        }

        return lines.join('\n')
    }, [summary, nodes.length, edges.length, activeWorkspace])

    const handleCopy = () => {
        navigator.clipboard.writeText(markdownText)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    if (!summaryOpen) return null

    return (
        <div style={{
            position: 'fixed', inset: 0, zIndex: 100,
            background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)',
            display: 'flex', alignItems: 'center', justifyContent: 'center'
        }}
            onClick={() => setSummaryOpen(false)}
        >
            <div
                onClick={e => e.stopPropagation()}
                style={{
                    width: 640, maxHeight: '80vh',
                    background: 'var(--k-bg-panel)',
                    border: '1px solid rgba(255,255,255,0.1)',
                    borderRadius: 14,
                    display: 'flex', flexDirection: 'column',
                    overflow: 'hidden',
                    boxShadow: '0 24px 64px rgba(0,0,0,0.6)',
                }}
            >
                {/* Header */}
                <div style={{ padding: '18px 22px', borderBottom: '1px solid var(--k-border-subtle)', display: 'flex', alignItems: 'center', gap: 10 }}>
                    <FileText size={18} color="var(--k-accent-blue)" />
                    <span style={{ fontSize: 16, fontWeight: 600, color: 'var(--k-text-primary)', flex: 1 }}>
                        Architecture Summary
                    </span>
                    <button onClick={handleCopy} style={{
                        display: 'flex', alignItems: 'center', gap: 5,
                        padding: '5px 10px', borderRadius: 6, fontSize: 12,
                        background: copied ? 'rgba(52,211,153,0.15)' : 'rgba(96,165,250,0.12)',
                        color: copied ? '#34d399' : '#60a5fa',
                        border: copied ? '1px solid rgba(52,211,153,0.3)' : '1px solid rgba(96,165,250,0.25)',
                        cursor: 'pointer',
                    }}>
                        {copied ? <Check size={13} /> : <Copy size={13} />}
                        {copied ? 'Copied!' : 'Copy Markdown'}
                    </button>
                    <button onClick={() => setSummaryOpen(false)} style={{ color: 'var(--k-text-dim)', padding: 4, borderRadius: 4 }}>
                        <X size={16} />
                    </button>
                </div>

                {/* Content */}
                <div style={{ flex: 1, overflowY: 'auto', padding: '20px 22px', display: 'flex', flexDirection: 'column', gap: 20 }}>
                    {!summary ? (
                        <p style={{ color: 'var(--k-text-dim)', fontSize: 14 }}>No graph data loaded yet. Open a workspace and scan it first.</p>
                    ) : (
                        <>
                            {/* Stats row */}
                            <div style={{ display: 'flex', gap: 12 }}>
                                {[
                                    { label: 'Nodes', value: nodes.length, color: '#60a5fa' },
                                    { label: 'Edges', value: edges.length, color: '#a78bfa' },
                                    { label: 'Types', value: Object.keys(summary.byType).length, color: '#34d399' },
                                ].map(s => (
                                    <div key={s.label} style={{ flex: 1, background: `${s.color}10`, border: `1px solid ${s.color}25`, borderRadius: 8, padding: '10px 14px' }}>
                                        <div style={{ fontSize: 22, fontWeight: 700, color: s.color }}>{s.value}</div>
                                        <div style={{ fontSize: 11, color: 'var(--k-text-dim)', marginTop: 2 }}>{s.label}</div>
                                    </div>
                                ))}
                            </div>

                            {/* Node types */}
                            <Section title="Nodes by Type">
                                {Object.entries(summary.byType).sort(([,a],[,b]) => b - a).map(([type, count]) => (
                                    <Row key={type} label={type.replace('_', ' ')} value={count} total={nodes.length} />
                                ))}
                            </Section>

                            {/* Edge types */}
                            <Section title="Connections by Type">
                                {Object.entries(summary.edgesByType).sort(([,a],[,b]) => b - a).map(([type, count]) => (
                                    <Row key={type} label={type} value={count} total={edges.length} />
                                ))}
                            </Section>

                            {/* Entry points */}
                            {summary.entryPoints.length > 0 && (
                                <Section title="Primary Entry Points">
                                    {summary.entryPoints.map(n => (
                                        <div key={n.id} style={{ fontSize: 12, color: 'var(--k-text-secondary)', padding: '3px 0', fontFamily: 'monospace' }}>
                                            {n.name} <span style={{ color: 'var(--k-text-dim)', fontFamily: 'sans-serif' }}>({n.type})</span>
                                        </div>
                                    ))}
                                </Section>
                            )}

                            {/* Hottest nodes */}
                            {summary.hotNodes.length > 0 && (
                                <Section title="🔥 Hottest Files">
                                    {summary.hotNodes.map((n, i) => (
                                        <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '4px 0' }}>
                                            <div style={{ width: 8, height: 8, borderRadius: '50%', background: heatToCss(n.heat), flexShrink: 0 }} />
                                            <span style={{ fontSize: 12, fontFamily: 'monospace', color: 'var(--k-text-primary)' }}>{n.name}</span>
                                            <span style={{ fontSize: 11, color: heatToCss(n.heat), marginLeft: 'auto' }}>{Math.round(n.heat * 100)}%</span>
                                        </div>
                                    ))}
                                </Section>
                            )}

                            {/* Coupling warnings */}
                            {summary.couplingWarnings.length > 0 && (
                                <Section title="⚠️ High-Coupling Nodes">
                                    {summary.couplingWarnings.map((w, i) => (
                                        <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '4px 0' }}>
                                            <span style={{ fontSize: 12, fontFamily: 'monospace', color: 'var(--k-text-primary)' }}>{w.name}</span>
                                            <span style={{ fontSize: 11, color: 'var(--k-text-dim)' }}>{w.type}</span>
                                            <span style={{ fontSize: 11, color: '#f87171', marginLeft: 'auto' }}>{w.radius} in blast radius</span>
                                        </div>
                                    ))}
                                </Section>
                            )}
                        </>
                    )}
                </div>
            </div>
        </div>
    )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div>
            <div style={{ fontSize: 11, color: 'var(--k-text-dim)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 8 }}>
                {title}
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                {children}
            </div>
        </div>
    )
}

function Row({ label, value, total }: { label: string; value: number; total: number }) {
    const pct = total > 0 ? (value / total) * 100 : 0
    return (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: 12, color: 'var(--k-text-secondary)', width: 130, flexShrink: 0, textTransform: 'capitalize' }}>{label}</span>
            <div style={{ flex: 1, height: 4, background: 'rgba(255,255,255,0.06)', borderRadius: 2 }}>
                <div style={{ height: '100%', width: `${pct}%`, background: 'rgba(96,165,250,0.5)', borderRadius: 2 }} />
            </div>
            <span style={{ fontSize: 12, color: 'var(--k-text-dim)', width: 28, textAlign: 'right' }}>{value}</span>
        </div>
    )
}
